[package]
edition = "2024"
license = "Apache-2.0"
name = "veecle-os-examples-orchestrator-ipc"
publish = false
version = "0.0.0"

[workspace]

[dependencies]
rand = { version = "0.9.2", default-features = false, features = ["std_rng"] }
veecle-ipc = { path = "../../veecle-ipc", default-features = false }
veecle-os = { path = "../../veecle-os", default-features = false, features = ["osal-std", "telemetry"] }
veecle-os-examples-common = { path = "../common", default-features = false, features = ["alloc", "telemetry"] }
veecle-telemetry = { path = "../../veecle-telemetry", default-features = false, features = ["enable"] }
