[package]
edition = "2024"
license = "Apache-2.0"
name = "veecle-os-examples-embassy-std"
publish = false
version = "0.0.0"

[workspace]

[dependencies]
embassy-executor = { version = "0.9.1", features = ["arch-std", "executor-thread", "log"] }
embassy-sync = { version = "0.7.2", features = ["log"] }
embassy-time = { version = "0.5.0", features = ["generic-queue-32", "std"] }
veecle-os = { path = "../../veecle-os", default-features = false, features = ["osal-embassy", "telemetry-enable"] }
veecle-os-examples-common = { path = "../common", default-features = false, features = ["alloc", "telemetry"] }
# TODO: Necessary for thread-local right now.
rand = { version = "0.9.2", default-features = false }
veecle-telemetry = { path = "../../veecle-telemetry", default-features = false, features = ["std"] }
