
# cargo-vet audits file

[[audits.macro_rules_attribute]]
who = "Wim Looman <wim.looman@veecle.io>"
criteria = "safe-to-run"
version = "0.2.2"
notes = "The crate consists of only re-exports and simple `macro_rules!`."

[[audits.macro_rules_attribute-proc_macro]]
who = "Wim Looman <wim.looman@veecle.io>"
criteria = "safe-to-run"
version = "0.2.2"
notes = "Very brief audit just to verify it doesn't do anything outside using proc-macro APIs."

[[audits.paste]]
who = "Wim Looman <wim.looman@veecle.io>"
criteria = "safe-to-deploy"
violation = "*"
notes = "We ignore the unmaintained advisory as we use it as a dev-dependency, but don't want it to become a real dependency"
