[package]
edition = "2024"
license = "Apache-2.0"
name = "veecle-os-examples-embassy-stm32"
publish = false
version = "0.0.0"

[workspace]

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"], default-features = false }
cortex-m-rt = { version = "0.7.5", default-features = false }
critical-section = { version = "1.2.0", default-features = false }
embassy-executor = { version = "0.9.1", features = ["arch-cortex-m", "executor-thread"], default-features = false }
embassy-net = { version = "0.7.1", features = ["medium-ethernet", "proto-ipv4"], default-features = false }
embassy-stm32 = { version = "0.4.0", features = [
  "memory-x",
  "rt",
  "single-bank",
  "stm32f767zi",
  "time-driver-any",
], default-features = false }
embassy-time = { version = "0.5.0", features = ["generic-queue-32"], default-features = false }
embedded-io-async = { version = "0.6.1", default-features = false }
heapless = { version = "0.8.0", default-features = false }
panic-halt = { version = "1.0.0", default-features = false }
static_cell = { version = "2.1.1", default-features = false }
veecle-os = { path = "../../veecle-os", features = ["osal-embassy"], default-features = false }
veecle-os-examples-common = { path = "../common", default-features = false }

[[bin]]
name = "veecle-os-examples-embassy-stm32"
test = false
bench = false

[[bin]]
name = "tcp-client"
test = false
bench = false

[[bin]]
name = "tcp-server"
test = false
bench = false

[[bin]]
name = "udp-client"
test = false
bench = false

[[bin]]
name = "udp-server"
test = false
bench = false

[lib]
test = false
bench = false
